[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
    "npm ci",
    "npm run build"
]

[start]
cmd = "./railway-start.sh"

